# Activity 5 - Proving Mathematical Properties

Import necessary libraries.

In [1]:
import matplotlib.pyplot as plt
import numpy as np

### Creating the array equivalence checking function.

Function to check if arrays are equal.

In [2]:
def checkArraysEqual(array1, array2):
    """
    A function that checks if two arrays are equal. This takes two Python lists as parameters.
    Usage: checkArraysEqual(list1, list2)
    --where list1 and list2 are variables whose data types are lists.
    """
    if len(array1) == len(array2): # Check length of the two lists if they are equal.
        for (x, y) in zip(array1, array2): # Iterate through both lists if the length of the lists are equal.
            if x != y: # Check if the current value of indexes are not equal.
                return False # Return 'False' to denote that the values in each list differs from one another.
        return True
    else: # Proceed here if the length of the two lists are not equal.
        return False # Return 'False' to denote that the values in each list differs from one another.

Declaring test arrays where the expected result is False due to difference in length.

In [3]:
x = [0, 1, 2, 3, 4]
y = [5, 6, 7, 8]

checkArraysEqual(x,y)

False

Declaring test arrays where the expected result is False due to difference in values.

In [4]:
x = [0, 1, 2, 3, 4]
y = [5, 6, 7, 8, 9]

checkArraysEqual(x,y)

False

Declaring test arrays where the expected result is False due to difference in arrangement of same values.

In [5]:
x = [0, 1, 2, 3, 4]
y = [5, 6, 7, 8, 9]

checkArraysEqual(x,y)

False

Declaring test arrays where the expected result is True.

In [6]:
x = [3, 1, 5, 2, 0]
y = [3, 1, 5, 2, 0]

checkArraysEqual(x,y)

True

## Mathematical Properties

### Commutative Property

The commutative property is expressed in the following mathematical form:<br>
<br>
$$
  a[n]*b[n] = b[n]*a[n]
$$
<br>
It states that the order in which signals can be convoluted can be exchanged.

Declaring arrays `a` and `b`.

In [7]:
a = [0, 1, 2, 3, 4]
b = [5, 6, 7, 8, 9]

$a[n] * b[n]$

In [8]:
result1 = np.convolve(a, b)
result1

array([ 0,  5, 16, 34, 60, 70, 70, 59, 36])

$b[n] * a[n]$

In [9]:
result2 = np.convolve(b, a)
result2

array([ 0,  5, 16, 34, 60, 70, 70, 59, 36])

Check that the results are the same.

In [10]:
checkArraysEqual(result1, result2)

True

### Associative Property

The associative property is expressed in the following mathematical form:<br>
<br>
$$
  (a[n]*b[n]) * c[n] = a[n] * (b[n]*c[n])
$$
<br>
It describes that two signals can be convolved to produce an intermediate signal, then convolve the intermediate signal with the third signal, and that the order of convolutions does not matter.

Declaring arrays `a`, `b`, and `c`.

In [11]:
a = [0, 1, 2, 3, 4]
b = [5, 6, 7, 8, 9]
c = [-1, -1, 0, 1, 1]

$(a[n] * b[n]) * c[n]$

In [12]:
result1 = np.convolve(a, b)
result1 = np.convolve(result1, c)
result1

array([   0,   -5,  -21,  -50,  -89, -109,  -90,  -35,   35,  104,  129,
         95,   36])

$a[n] * (b[n] * c[n])$

In [13]:
result2 = np.convolve(b, c)
result2 = np.convolve(a, result2)
result2

array([   0,   -5,  -21,  -50,  -89, -109,  -90,  -35,   35,  104,  129,
         95,   36])

Check that the results are the same.

In [14]:
checkArraysEqual(result1, result2)

True

### Distributive Property

The distributive property is expressed in the following mathematical form:<br>
<br>
$$
  a[n]*b[n] + a[n]*c[n] = a[n] * (b[n]+c[n])
$$
<br>
It describes the operation of parallel systems with added outputs. It states that two or more systems can share the same input and have their outputs added, and produce the same results.

Declaring arrays `a`, `b`, and `c`.

In [15]:
a = [0, 1, 2, 3, 4]
b = [5, 6, 7, 8, 9]
c = [-1, -1, 0, 1, 1]

$a[n]*b[n] + a[n]*c[n]$

In [16]:
result1 = np.add(np.convolve(a, b), np.convolve(a, c))
result1

array([ 0,  4, 13, 29, 54, 69, 75, 66, 40])

$a[n] * (b[n]+c[n])$

In [17]:
result2 = np.convolve(a, np.add(b,c))
result2

array([ 0,  4, 13, 29, 54, 69, 75, 66, 40])

Check that the results are the same.

In [18]:
checkArraysEqual(result1, result2)

True

### Transference Between Input and Output

The transference between input and output property is expressed as following:<br>
<br>
$$
  x[n]*h[n] = y[n]\\
    same\ linear\ change\ on\ x\ and\ y  \\
  x'[n]*h[n] = y'[n] 
$$
<br>

$$
    y_{1}'[n] = x'[n]*h[n]
$$
<br>

$$
    x[n]*h[n] = y[n]\\
    y[n]\ undergoes\ same\ linear\ change\ as\ x\ = y_{2}'[n]
$$
<br>

$$
    y_{1}'[n] = y_{2}'[n]
$$
<br>

It states that suppose the input signal is generating an output signal. If the same input signal is changed in some linear way, resulting in a new input signal, the resulting output signal is changed in the exact same linear way that the input signal was changed.

Declaring arrays `x`, `h` and the `linear_change` value.

In [19]:
x = [0, 1, 2, 3, 4]
h = [5, 6, 7, 8, 9]
linear_change = 3

$x[n]*h[n] = y[n]$

In [20]:
y = np.convolve(x, h)
y

array([ 0,  5, 16, 34, 60, 70, 70, 59, 36])

$x'[n]*h[n] = y_{1}'[n]$

In [21]:
x_change = np.multiply(x, linear_change)
y_change1 = np.convolve(x_change, h)
y_change1

array([  0,  15,  48, 102, 180, 210, 210, 177, 108])

$y[n]\ undergoes\ same\ linear\ change\ as\ x = y_{2}'[n]$

In [22]:
y_change2 = np.multiply(y, linear_change)
y_change2

array([  0,  15,  48, 102, 180, 210, 210, 177, 108])

Check that the results are the same ($y_{1}'[n] = y_{2}'[n]$).

In [23]:
checkArraysEqual(y_change1, y_change2)

True